### ISSUE TITLE
Video Download Issue

### ISSUE THREAD

**Issue by Kavorka9** [monkeyWie/gopeed-extension-youtube#10]
When I attempt to download a video it downloads a text file called "watch" instead.

<img width="1888" alt="Gospeed youtube extension" src="https://github.com/user-attachments/assets/9aec11a6-909d-4926-aceb-623f784dd71f">

**Comment by muhammetaliaydin** [comment]
I got same error.

**Comment by monkeyWie** [comment]
What's gopeed version and extension version?

**Comment by Kavorka9** [comment]
Gopeed: 1.5.8
Youtube Extension: 1.3.0

**Comment by monkeyWie** [comment]
Alright, please post extension.log

**Comment by Kavorka9** [comment]
Here you go.

**Comment by muhammetaliaydin** [comment]
Gopeed: 1.5.7
Youtube extention: 1.3.0

extention.log:
2024-08-24 13:37:58 ERR [monkeyWie@youtube] call function failed: onResolve error="SyntaxError: Invalid flags supplied to RegExp constructor 's'"
2024-08-24 13:41:13 ERR [monkeyWie@youtube] call function failed: onResolve error="SyntaxError: Invalid flags supplied to RegExp constructor 's'"
2024-08-25 21:34:16 ERR [monkeyWie@youtube] call function failed: onResolve error="SyntaxError: Invalid flags supplied to RegExp constructor 's'"
2024-08-24 13:37:58 ERR [monkeyWie@youtube] call function failed: onResolve error="SyntaxError: Invalid flags supplied to RegExp constructor 's'"
2024-08-24 13:41:13 ERR [monkeyWie@youtube] call function failed: onResolve error="SyntaxError: Invalid flags supplied to RegExp constructor 's'"
2024-08-25 21:34:16 ERR [monkeyWie@youtube] call function failed: onResolve error="SyntaxError: Invalid flags supplied to RegExp constructor 's'"

**Comment by muhammetaliaydin** [comment]
I updated to version 1.5.8 and i got still same error.
Also i'm using gopeed on casaos with docker image.

**Comment by monkeyWie** [comment]
I tested it on docker version 1.5.8 and it work well:

![GIF 2024-8-26 8-57-36](https://github.com/user-attachments/assets/df15ebb0-bc29-42d4-8fad-d220f9d24856)

Could you submit a new extension.log?

**Comment by ixoomr** [comment]
有些链接可以成功解析出来 ，有些不行
如：https://www.youtube.com/watch?v=szx5FCIdYVc
![屏幕截图 2024-09-17 085626](https://github.com/user-attachments/assets/a127d47d-1ad2-4002-a79a-407c257d4809)
如：https://www.youtube.com/watch?v=hf6zgmubXFU
![屏幕截图 2024-09-17 090018](https://github.com/user-attachments/assets/3895b83a-cd87-4b25-b73d-bcff1f868190)

**Comment by ixoomr** [comment]
版本都是最新，线路没有任何问题。

**Comment by ixoomr** [comment]
有些可以解析成功，有些不能，和楼上一样错误。
比如这个：https://www.youtube.com/watch?v=hf6zgmubXFU

**Comment by Qiubihuang** [comment]
很多短视频解析失败
参考短视频链接：https://www.youtube.com/shorts/PHtucBU7Ltk
Many short videos fail to parse
Reference short video link: https://www.youtube.com/shorts/PHtucBU7Ltk
![Clip_2024-09-18_21-01-12](https://github.com/user-attachments/assets/fdc36045-d4a7-4205-8121-307b9086f49b)

**Comment by monkeyWie** [comment]
> 很多短视频解析失败 参考短视频链接：https://www.youtube.com/shorts/PHtucBU7Ltk Many short videos fail to parse Reference short video link: https://www.youtube.com/shorts/PHtucBU7Ltk ![Clip_2024-09-18_21-01-12](https://private-user-images.githubusercontent.com/26588823/368577845-fdc36045-d4a7-4205-8121-307b9086f49b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDI4NDQsIm5iZiI6MTcyNjc0MjU0NCwicGF0aCI6Ii8yNjU4ODgyMy8zNjg1Nzc4NDUtZmRjMzYwNDUtZDRhNy00MjA1LTgxMjEtMzA3YjkwODZmNDliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDEwNDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODM3ZDFkYjgzNDY4OGU4ZjkyNTQ2YmU2NzA1MDk1Njk3OTgxYmZjYWRkNzBmOTlhNjI2ZDg0OGNkODEzNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E1F1s9OINnMj5I6dG2KNzxP-NjKe5iGSFoR9HpZfmh8)

Thank, I'll fix it on gopeed 1.5.10

**Comment by monkeyWie** [comment]
> 很多短视频解析失败 参考短视频链接：https://www.youtube.com/shorts/PHtucBU7Ltk Many short videos fail to parse Reference short video link: https://www.youtube.com/shorts/PHtucBU7Ltk ![Clip_2024-09-18_21-01-12](https://private-user-images.githubusercontent.com/26588823/368577845-fdc36045-d4a7-4205-8121-307b9086f49b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTQ0MjIsIm5iZiI6MTcyNzAxNDEyMiwicGF0aCI6Ii8yNjU4ODgyMy8zNjg1Nzc4NDUtZmRjMzYwNDUtZDRhNy00MjA1LTgxMjEtMzA3YjkwODZmNDliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDE0MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwN2ZhZmE3ODA4YTI5MTBjMWM4NTAyOTc0NTM1ZjE4MzI0NGEyY2UwNWNiZmE1ODBiZDcwNTI5NDFjNjc1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kOtzWQMZRVrwjWTEuFK0rhxI0OlmwlgUDBfXnMuW1Qg)

Please try 1.6.0

**Comment by Kavorka9** [comment]
It's working! Thanks so much!
