### ISSUE TITLE
下载youtube视频的异常

### ISSUE THREAD

**Issue by x1ntt** [monkeyWie/gopeed-extension-youtube#2]
例子链接: https://www.youtube.com/watch?v=jh4C7w-dvho

创建任务的时候需要选中`直接下载`，否则不会开始，如果直接开始，下载到的东西如下
![image](https://github.com/monkeyWie/gopeed-extension-youtube/assets/31797165/be4f9923-19fb-41be-995f-b4e9e866545f)
看起来是`youtube`的视频切片？这不能被`potplayer`播放

另外，这个能下载4k清晰度的视频吗？

**Comment by monkeyWie** [comment]
勾选直接下载时，扩展不会生效，所以下载的就是个网页，然后你这个链接我测试了下是可以的啊

![image](https://github.com/monkeyWie/gopeed-extension-youtube/assets/13160176/1ad49ee4-012f-472e-a7fa-95ecae235383)

**Comment by monkeyWie** [comment]
4k目前还不支持，因为Youtube高质量的视频视频和音频是分开的，下完之后得用ffmpeg合并，目前我默认只下载有音频的视频，后面可以提供个选项来支持

**Comment by x1ntt** [comment]
> 勾选直接下载时，扩展不会生效，所以下载的就是个网页，然后你这个链接我测试了下是可以的啊
> 
> ![image](https://private-user-images.githubusercontent.com/13160176/291183790-1ad49ee4-012f-472e-a7fa-95ecae235383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODYzOTIsIm5iZiI6MTcwMjg4NjA5MiwicGF0aCI6Ii8xMzE2MDE3Ni8yOTExODM3OTAtMWFkNDllZTQtMDEyZi00NzJlLWE3ZmEtOTVlY2FlMjM1MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3NTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OGJkODU3MmY1ZjMxOTNlYmIzYzNiYjk5NDQ5MmJhOWMwNGE4YmYxN2NmMzc5ZDJkMjYyN2FkNTE2NGM3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t5fVIdyWDnWlehonxoKeJ7zJCSIuEWN0b-G4CsHBHyk)

+ 原来是网页吗？我看它请求了很多以为是视频切片
+ 看起来是我网络之前出了问题，开始按钮变成圆圈之后一直转，然后就又变成开始按钮了
----

> 4k目前还不支持，因为Youtube高质量的视频视频和音频是分开的，下完之后得用ffmpeg合并，目前我默认只下载有音频的视频，后面可以提供个选项来支持
+ 期待这个功能，预计什么时候有呢？或者现在有这样的下载方案吗？目前找到在线下载都是没有高清选项的

**Comment by quan778633** [comment]
我安装你的扩展，下载油管视频打不开，不完整视频

**Comment by amorous-monk** [comment]
无法正常使用，错误：http request fail 429

**Comment by ddunniu** [comment]
能不能弄成只输入https://www.youtube.com/watch?v=后边的代码就可以下载，前面都是固定的。

**Comment by zyn2025146110** [comment]
我下载YouTube视频时一直显示错误，这是怎么回事。

**Comment by Stanley-baby** [comment]
解决了吗？好像不能下载 YouTube

**Comment by monkeyWie** [comment]
> > 勾选直接下载时，扩展不会生效，所以下载的就是个网页，然后你这个链接我测试了下是可以的啊
> > ![image](https://private-user-images.githubusercontent.com/13160176/291183790-1ad49ee4-012f-472e-a7fa-95ecae235383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODYzOTIsIm5iZiI6MTcwMjg4NjA5MiwicGF0aCI6Ii8xMzE2MDE3Ni8yOTExODM3OTAtMWFkNDllZTQtMDEyZi00NzJlLWE3ZmEtOTVlY2FlMjM1MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3NTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OGJkODU3MmY1ZjMxOTNlYmIzYzNiYjk5NDQ5MmJhOWMwNGE4YmYxN2NmMzc5ZDJkMjYyN2FkNTE2NGM3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t5fVIdyWDnWlehonxoKeJ7zJCSIuEWN0b-G4CsHBHyk)
> 
> * 原来是网页吗？我看它请求了很多以为是视频切片
> * 看起来是我网络之前出了问题，开始按钮变成圆圈之后一直转，然后就又变成开始按钮了
> 
> > 4k目前还不支持，因为Youtube高质量的视频视频和音频是分开的，下完之后得用ffmpeg合并，目前我默认只下载有音频的视频，后面可以提供个选项来支持
> 
> * 期待这个功能，预计什么时候有呢？或者现在有这样的下载方案吗？目前找到在线下载都是没有高清选项的

1.1.0已经支持，需要在扩展设置里开启`Separate Streams`
