### ISSUE TITLE
使用 youtube APP 分享出来的链接，无法下载

### ISSUE THREAD

**Issue by gaupen1186** [monkeyWie/gopeed-extension-youtube#3]
如题。
点击分享按钮出来的链接如下，无法下载
https://youtu.be/Xc7d7F5T6rI?si=ayGqIKidkK0_itdh
而浏览器里的地址如下，可以下载
https://www.youtube.com/watch?v=Xc7d7F5T6rI

**Comment by monkeyWie** [comment]
新版本已经支持了，升级的1.0.5即可
