### ISSUE TITLE
youtube不能自动下载最高清晰度的带音频的视频

### ISSUE THREAD

**Issue by jackiegk** [monkeyWie/gopeed-extension-youtube#4]
视频链接：https://www.youtube.com/watch?v=EtHk0dZOs9o

扩展直接下载下来的是360P的

通过第三方网站是可以下载出1280*720视频的
https://youtube.iiilab.com/
![image](https://github.com/monkeyWie/gopeed-extension-youtube/assets/4899825/1467d11a-fd8f-4636-9f1a-7b371bdea79d)

![image](https://github.com/monkeyWie/gopeed-extension-youtube/assets/4899825/4634582f-26f8-4ae3-9a1a-1d1b56851bf5)

**Comment by seramat** [comment]
Same problem here. Original quality is 4K, but downloaded 720P video.

**Comment by zdiovo** [comment]
Same problem here. Original quality is 4K, but downloaded 720P video.

**Comment by korboybeats** [comment]
Same , max quality is 4k but it's only downloading 360p for me.

**Comment by monkeyWie** [comment]
Please update to 1.1.0 and enable separate streams.
