### ISSUE TITLE
添加youtube下载后，下载速率不跑，无法下载youtube视频

### ISSUE THREAD

**Issue by michealhansun** [monkeyWie/gopeed-extension-youtube#9]
![image](https://github.com/user-attachments/assets/529c1eaa-62b1-4a53-9fb9-72cc67afdefa)

**Comment by Ftwrr** [comment]
same issue here

**Comment by monkeyWie** [comment]
升级gopeed版本到1.5.8，然后扩展也升级到最新就可以了
